[project]
name = "grpo-synthesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "safetensors>=0.5.3",
    "tokenizers>=0.21.1",
    "torch>=2.6.0",
]
